# Generated by Django 5.2.17 on 2026-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_teammembership_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='Task_task_project_a96d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='Task_task_status_e12786_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='Task_task_assigne_653509_idx'),
        ),
    ]
